### ISSUE TITLE
5.4.1.D revert X axis, looks funny (consult with professors)

### ISSUE THREAD

**Issue by carlosscastro** [carlosscastro/similarity_261#3]
Note that in the charts in 5.4.1.D, the numbers in the x axis are reverted. The code from the professors reverts it on purpose. We should check with professors and revert sorting if needed.

**Comment by mathaholic** [comment]
Done
http://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.invert_xaxis.html
ax.invert_xaxis()

**Comment by mathaholic** [comment]
I verified with the Kyle that the axis did indeed need to be changed so it was smallest -> largest  
See below:
nikkih 
[Yesterday at 7:59 PM] 
in w261-summer-2017
hi there @kylehamilton @jameswine @jimiucb in the histograms, one of prints out as an inverted axis.  I was going to fix this, but @carlosscastro thinks this was perhaps by design? Which view would you rather see? the inverted x-axis, or an x axis that ranges from 0 onwards?

1 reply
kylehamilton [13 hours ago] 
nikkih: I’m assuming you are referring to the histogram of 5-gram lengths. The x-axis should go from min to max. The plot code was written to deal with the input format - it looks like some transformation had to be done. Depending on how you write your own solution, you may need to adjust the code for the plot.
